name: Cross-platform Rust Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'The git tag to release (e.g., v1.2.3)'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: kilo-CLI
            asset_name: kilo-CLI-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            bin: kilo-CLI
            asset_name: kilo-CLI-macos-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: kilo-CLI.exe
            asset_name: kilo-CLI-windows-amd64.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Run tests on macOS
        if: matrix.os == 'macos-latest'
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: cargo test --release --target ${{ matrix.target }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.asset_name }}
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: success()

    env:
      TAG_NAME: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.tag }}

    steps:
      - name: Download all release binaries
        uses: actions/download-artifact@v4
        with:
          name: '*'
          path: binaries

      - name: Flatten artifacts
        run: |
          mkdir -p binaries_flat
          find binaries -type f -exec mv {} binaries_flat/ \;

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries_flat/kilo-CLI-linux-amd64
          asset_name: kilo-CLI-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries_flat/kilo-CLI-macos-amd64
          asset_name: kilo-CLI-macos-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries_flat/kilo-CLI-windows-amd64.exe
          asset_name: kilo-CLI-windows-amd64.exe
          asset_content_type: application/octet-stream
